name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chorehero_api_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1

      - name: Install dependencies
        run: |
          cd chorehero-api
          gem install bundler
          bundle install

      - name: Set up test database
        run: |
          cd chorehero-api
          cp config/database.yml.github config/database.yml
          bin/rails db:create db:migrate

      - name: Run tests
        run: |
          cd chorehero-api
          bin/rails test
          
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: justinmorgan21

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Rails backend
        uses: docker/build-push-action@v5
        with:
          context: ./chorehero-api
          push: true
          tags: justinmorgan21/chorehero-backend:latest,justinmorgan21/chorehero-backend:${{ github.sha }}

      - name: Build and push React frontend
        uses: docker/build-push-action@v5
        with:
          context: ./chorehero-frontend
          push: true
          tags: justinmorgan21/chorehero-frontend:latest,justinmorgan21/chorehero-frontend:${{ github.sha }}

      - name: Trigger Render deploy (Rails API)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

      - name: Trigger Render deploy (React Frontend)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
